version: '3'
services:
  ola:
    container_name: ola
    image: 'ghcr.io/Renaud11232/ola'
    volumes:
      - ./config:/home/olad/.ola
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/bus/usb/001/005:/dev/bus/usb/001/005
    restart: unless-stopped
    network_mode: host
